### ISSUE TITLE
Unable to change settings after a while in-game

### ISSUE THREAD

**Issue by PapaDimitri** [SpluoSplatus/Vanilla-Refresh#10]
So i changed some setting using /function and after some time when i try to do it again i can open the main menu of settings but when i try to click for example "player" settings theres nothing to click. The the only fix i have found is resetting all settings back to default then they are working again.

**Comment by SpluoSplatus** [comment]
are you using other plugins/datapacks/mods? are you messing with your worlds scoreboard.dat? something else is likely interfering and causing issues

**Comment by PapaDimitri** [comment]
Oh my god... I wish i knew that i have 230 mods lmao

**Comment by SpluoSplatus** [comment]
with that many mods, there’s always potential for incompatibility, and it definetly seems like one. if you end up finding the incompatible mod/a solution to this, it would be great if you sent it here 

if you’d like to try and find the mod causing the issue here’s a method for doing so (though it will take a bit to do if you have 100 mods haha…)

 > “Sometimes, when you are trying to figure out your issue, you need to use the "remove until it stops crashing" method. Here is an efficient way to do so:
> - Divide your mods in half: Half A and Half B.
> - Add Half A to your game/server, and start.
> - If it crashes, remove half of Half A.
> - If it does not crash, add half of Half B.
> - Repeat the process until it's narrowed down to the culprit!”

**Comment by PapaDimitri** [comment]
Yea... That will take a week to do. I  tried to find 1 incompatible mod that didnt rly show up on log or i couldnt read that out and it took 2 hours it was 100 mods then

**Comment by PapaDimitri** [comment]
Also is there a way to set default settings? I did it once in my old modpack but now i cant find the right folder and .json

**Comment by SpluoSplatus** [comment]
Checkout this guide ->>  https://github.com/SpluoSplatus/Vanilla-Refresh/wiki/Changing-Default-Settings
Much better than old method which involved directly modifying files, this new method works with new updates and switching versions

**Comment by PapaDimitri** [comment]
Yea i directly modified the stuff inside .jar. Also i was thinking a little bit and idk if i m right but vanilla tweaks(or traveles titles???) does something scoreboard i think. I ll check it tomarrow. Thanks

**Comment by PapaDimitri** [comment]
I downloaded the default settings configured, saved it, put it in mods folder aaaand it doesnt work lol. I m not sure if it should work when i reset all settings via /function

**Comment by PapaDimitri** [comment]
I think i found default settings path in mod itself 
tho. data/vanilla-refresh/functions/other/default settings.mcfunction

**Comment by SpluoSplatus** [comment]
when resetting settings, it only works on the latest version of vanilla refresh (1.4.23)
however if you create a new world you’ll see your new configured defaults

**Comment by SpluoSplatus** [comment]
would recommend joining my discord for help as we’re making a tangent on a GitHub issue https://discord.gg/6GXZyKjR93
