### ISSUE TITLE
中文更新Chinese update

### ISSUE THREAD

**Issue by yzklpaa** [SpluoSplatus/Vanilla-Refresh#13]
Your work has been translated into Chinese, and I hope you can adopt it:)
[k_zh_cn.json](https://github.com/user-attachments/files/16440011/k_zh_cn.json)

**Comment by SpluoSplatus** [comment]
You've got basically everything actually, just one new line that was added:

`"Add an item to this Armor Stand first to create an item rack": "translation",`

Once those are implemented and you let me know for which Chinese localizations I should put this for (simplified for e.x. or another one), I’ll implement it soon.

**Comment by yzklpaa** [comment]
Okay, I'm done.I hope it can be adopted by you
[zh_cn.json](https://github.com/user-attachments/files/16454925/zh_cn.json)
