### ISSUE TITLE
Can't disable the day counter

### ISSUE THREAD

**Issue by nunomago** [SpluoSplatus/Vanilla-Refresh#14]
**Description**
I would like the day counter to be visible whenever the day passes, for example when I sleep in a bed but as it stands the day counter is always showing and can't be turned off. No matter which setting I try setting it to (1, 2, or 0).

**Steps To Reproduce**
(optional)
Tried disabling it via the chat GUI and also via the defaults datapack injection.

**Minecraft Version:** 1.21 server with paper

Bug reports reviewed under the assumption that you are on the latest version of Vanilla Refresh. Optionally, feel free to insert any screenshots or extra info if needed. (you can erase this text!)

**Comment by SpluoSplatus** [comment]
Do you mean the clock day counter or f3 day counter? If it’s not disabling this is another day counter then that’s tied to another feature (clock one is readable clocks and the f3 one is a vanilla feature)

**Comment by nunomago** [comment]
> Do you mean the clock day counter or f3 day counter? If it’s not disabling, then this is another day counter that’s tied to another feature (clock one is readable clocks and the f3 one is a vanilla feature)

I mean this one, above the XP, health and food bars. I assume it is the day counter from this mod, since I'm not using another day counter right now. 
![image](https://github.com/user-attachments/assets/360bccba-7231-40bc-b96c-99a65b09711f)

I did generate the world with another separate day counter mod as a datapack but installed vanilla-refresh afterwards since it's packed with a lot more features. I basically removed that separate day counter mod and am now using vanilla-refresh as a datapack in the same world.

Do you think it's required to generate a new world for this mod to work as a datapack? 🤔

**Comment by nunomago** [comment]
I generated a new world using vanilla-refresh and it seems to work as intended. The previous daycounter mod that I used to generate my previous world seems to overlap with this one, even though it's not loaded anymore.

Either way thanks for the help!
