### ISSUE TITLE
Not an Issue, just a request.

### ISSUE THREAD

**Issue by Manke5005** [SpluoSplatus/Vanilla-Refresh#15]
Hey there! I absolutely love your vanilla refresh pack, especially how you edited the baby zombie to have lower health. I am somewhat vaguely familiar with fabric modding, but I have no idea how the mcfunction stuff works that you used with vanilla refresh. Is there ANY possible way you could go out of your way (please haha) to put together a single-featured mod that does whatever it is that you did for the baby zombie, but rather, for the warden? Like lower his health to about 100 hp instead of 500? Apparently there is no way to mod anything like that through regular means, and you've been the only one I've seen so far who has somehow put a fabric-capable mod out with this type of entity health edit that I'm looking for! Sorry for the long request and hopefully it doesn't sound all over the place. Not holding my breath for a response because I know this is a strange and annoying request. Thank you for considering!

**Comment by SpluoSplatus** [comment]
requests are okay, but it’s more geared to improving (enhancing) vanilla refresh.

as for making a new pack lowering the warden’s health, I won’t be doing this. The warden’s gimic is closely tied to the fact it’s basically unkillable. 

But the baby zombies feature is very simply made, mc functions are just commands, as Vanilla Refresh is just a datapack packaged as a mod. Check out this file path within the datapack and view it with any text editor for reference: data/vanilla_refresh/other/clocks/20tick

join my discord if you need help and ask in #datapack-development https://discord.gg/XZVARKkjwt
