### ISSUE TITLE
PLAYER HEAD DROPS

### ISSUE THREAD

**Issue by ZroBix** [SpluoSplatus/Vanilla-Refresh#18]
Took me awhile trying to find what mod was causing my player-head to drop when I died. SPOILER, IT'S THIS ONE. WHY? And why is it not stated in the mod discription anywhere? (sorry no disrespect, just a little annoying).

Perhaps its a bug with the 'Wither Drops Head' feature.

Mod - [1.20.x] ~ 1.4.19h
Minecraft - 1.20.1

EDIT: FOUND SETTING TO TURN IT OFF.
so not a bug lol.

**Comment by SpluoSplatus** [comment]
my bad! ive now just edited the modrinth page to mention the feature
