### ISSUE TITLE
How to change default settings while using it as server-side datapack?

### ISSUE THREAD

**Issue by HiraMafu** [SpluoSplatus/Vanilla-Refresh#20]
Since the [tutorial](https://github.com/SpluoSplatus/Vanilla-Refresh/wiki/Changing-Default-Settings) only display a way to save it as a mod, I would like to know how to change the setting while using it as a datapack.

**Comment by SpluoSplatus** [comment]
to use it as a datapack just keep it as .zip and drag it into your datapacks folder
note: editing settings can easily be done on servers by using `/function vanilla_refresh:_settings` ingame
