### ISSUE TITLE
Soul link doesn't appear if used with any other mod like "Gravestones" or "Corpse"

### ISSUE THREAD

**Issue by game822snake** [SpluoSplatus/Vanilla-Refresh#21]
**Description**
When used with mods that save items after death like:
https://www.curseforge.com/minecraft/mc-mods/gravestone-mod
or 
https://www.curseforge.com/minecraft/mc-mods/corpse
and setting KeepInventory to false Soul link just doesn't appear. 

**Steps To Reproduce**
1. Install either of the above mods
2. Enable soul link
3. Disable "Store Items"
4. Set KeepInventory to false
5. die

**Minecraft Version:** 1.20.1

Bug reports reviewed under the assumption that you are on the latest version of Vanilla Refresh. Optionally, feel free to insert any screenshots or extra info if needed. (you can erase this text!)

**Comment by SpluoSplatus** [comment]
soul links will not function if keep inventory is set to false. this is intentional behavior as it is what it relies on to check what items you have. 

you'll have to choose between these 3 death storing features which ones you prefer.
