### ISSUE TITLE
Player max health expected to be 20 regardless of what it actually is(compatability issue with mods & datapacks)

### ISSUE THREAD

**Issue by Bowswa** [SpluoSplatus/Vanilla-Refresh#22]
**Description**
When a mod/datapack modifies the max health of the player, it creates unexpected issues with the hotbar display as it expects the player's max health to be 20 at all times, regardless of if it actually modified or not.

**Steps To Reproduce**
(optional)
1. Use an origin or other mod/datapack that modifies the player's health
2. be near another player
3. the viewing player will see the bugged health
3a. max health going above will be something like 24/20
3b max health going lower will be something like 16/

**Minecraft Version:** 1.20.1 (no bug fix included in changelogs since)

**Comment by SpluoSplatus** [comment]
confirmed! will add functionality for this soon. 
note that when this is patched it will only be patched for the latest 1.21 versions
for now, you can address this by manually setting health with this command: `/scoreboard players set @s refresh_maxhealth 20` <<edit that number

**Comment by SpluoSplatus** [comment]
bug fixed! [fixed in latest 1.21 version 1.4.24e](https://modrinth.com/datapack/vanilla-refresh/version/1.4.24e)
