### ISSUE TITLE
In some scenarios where you die in a too tight room with the gravestones activated, you can lose some items when destroying the grave.

### ISSUE THREAD

**Issue by DrackWalker** [SpluoSplatus/Vanilla-Refresh#29]
**Description**
Just as the title says.

**Steps To Reproduce**
1. Build a little room
2. A full inventory is not needed
3. Die
4. Break the grave before regaining your stuff
5. Verify if you have everything when grabbing your stuff
![2024-11-18_23 26 19](https://github.com/user-attachments/assets/fadcb359-8e73-41d9-8cf0-57e8cc2265e9)
![2024-11-18_23 26 48](https://github.com/user-attachments/assets/3cdac6ba-bdc3-4953-909b-3e337ea6c1fe)
![2024-11-18_23 26 53](https://github.com/user-attachments/assets/7409bf4b-e650-4e40-b978-53edfbd27b88)
![2024-11-18_23 28 46](https://github.com/user-attachments/assets/2e9ca6bb-854a-434b-a838-2abbf16df882)
![2024-11-18_23 29 09](https://github.com/user-attachments/assets/507aa581-3fb6-46fd-8b46-8cabafdfa197)

**Minecraft Version:** 1.21.1

**Comment by SpluoSplatus** [comment]
i believe, funnily enough, this will only occur with dirt (or the terrain the gravestone places on)
i'll look further into it though, lmk if this occurs with other items

**Comment by DrackWalker** [comment]
I took dirt just for the exemple but my friend did lose his Mace when it happened to him, if you want I can test with other items and terrain on my side.

**Comment by SpluoSplatus** [comment]
bug has now been resolved! thank you for the report, if somehow the issue still occurs, let me know https://modrinth.com/datapack/vanilla-refresh/version/1.4.26
