### ISSUE TITLE
Looping Jukebox breaks discs

### ISSUE THREAD

**Issue by junieclipse** [SpluoSplatus/Vanilla-Refresh#8]
**Description**
Enabling Looping Jukebox prevents music discs from playing sound when inserted into a jukebox.

**Expected Behaviour**
1. Enable Looping Jukebox
2. Insert music disc into Jukebox
3. Listen to the music disc on repeat

**Actual Behaviour (Steps to reproduce bug)**
1. Enable Looping Jukebox
2. Insert music disc into Jukebox
3. Notice the lack of music playing

**Minecraft Version:** 1.21, Fabric Loader 0.16.0

**Comment by SpluoSplatus** [comment]
bug is confirmed! fixed now in v1.4.22c
