### ISSUE TITLE
Some crops don't give experience when broken

### ISSUE THREAD

**Issue by byxea** [SpluoSplatus/Vanilla-Refresh#9]
**Description**
Potatoes, pitcher crops, and torchflowers don't give experience when mined with Crop XP enabled.

**Steps To Reproduce**
1. Load in a world
2. Enable Crop XP with `/function vanilla_refresh:other/actions/block/crops_enable`, or click through config menu `/function vanilla_refresh:_settings`
3. Mine fully grown potatoes, pitcher pods, and torch flowers.
4. See that you have not gained any experience from these crops.

**Minecraft Version:** 1.21

**Vanilla Refresh Version**: 1.4.22c (mod)

**Other mods**: Sodium 0.5.11

**Video**: Footage of me breaking every plant that should grant experience when harvested.

https://github.com/user-attachments/assets/6dbbeec4-2161-4a19-9ba4-2268d8e1e4ee

**Comment by SpluoSplatus** [comment]
Bug fixed has now been fixed: Potatoes now drop XP in [1.4.22d](https://modrinth.com/datapack/vanilla-refresh/version/1.4.22d)
Note this behavior is intentional for torch flowers and pitcher plants

**Comment by SpluoSplatus** [comment]
Bug fixed has now been fixed: Potatoes now drop XP in [1.4.22d](https://modrinth.com/datapack/vanilla-refresh/version/1.4.22d)
Note this behavior is (currently) intentional for torch flowers and pitcher plants, but may be implemented as a feature at a later time

**Comment by SpluoSplatus** [comment]
Bug has now been fixed: Potatoes now drop XP in [1.4.22d](https://modrinth.com/datapack/vanilla-refresh/version/1.4.22d)
Note this behavior is (currently) intentional for torch flowers and pitcher plants, but may be implemented as a feature at a later time

**Comment by SpluoSplatus** [comment]
potatoes bug fixed! fixed in release [1.4.23](https://modrinth.com/datapack/vanilla-refresh/version/1.4.23)
